feat: Log http response body in debug mode
odpf/firehose pull request #95
Opened 2021-08-23 08:45 UTC by MayurGubrele

- Adding functionality to log HTTP response body when log_level=debug
- Classes affected: AbstractHttpSink.java, HttpSinkTest.java, PromSinkTest.java

2021-09-01 02:27 UTC, lavkesh commented on src/main/java/io/odpf/firehose/sink/http/SerializableHttpResponse.java
> +public class SerializableHttpResponse implements Serializable {
what is the purpose of this class? 
we can just call the debug method, if debug level is enabled.

2021-09-01 02:28 UTC, lavkesh commented on src/main/java/io/odpf/firehose/sink/common/AbstractHttpSink.java
> +        return response != null;
shouldn't this return true if the debug level is enabled?

2021-09-01 02:35 UTC, lavkesh commented on src/main/java/io/odpf/firehose/sink/common/AbstractHttpSink.java
> +        return response != null;
we can add a method in instrumentation if not already there.
and call that
```
 if (instrumentation.isDebugEnabled()) {
    instrumentation.logDebug("");
 }
 ```

2021-09-06 10:10 UTC, arujit approved these changes

2021-09-06 10:11 UTC, arujit commented
@MayurGubrele this branch has some conflicts right now. Can you please check and update things accordingly. Will merge post that.

2021-09-07 08:55 UTC, lavkesh commented
Let's check the instrumentation.isDebugEnabled() before called the instrumentation.debug() as the parameter evaluation cost is relatively more.. It's a standard practice, please read it here. 
https://logging.apache.org/log4j/1.2/manual.html#Performance

Let's remove the SerializableHttpResponse class entirely, It's not needed.

2021-09-07 08:57 UTC, lavkesh requested changes
Let's check the instrumentation.isDebugEnabled() before calling the instrumentation.debug() as the parameter evaluation cost is relatively more.. It's a standard practice, please read it here.
https://logging.apache.org/log4j/1.2/manual.html#Performance

Let's remove the SerializableHttpResponse class entirely, It's not needed.

2021-09-10 04:42 UTC, lavkesh approved these changes

2021-09-10 04:45 UTC, merged